a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print("Sum is :",(a+b))
print("Sub is :",(a-b))
print("Mul is :",(a*b))
print("Div is :",(a/b))
print("Square is :",(a**b))
print("Quotent is :",(a//b))
print("Reaminder is: ",(a%b))

